In [1]:
%run base.ipynb

<h1>System Inertia Matrix example</h1>

In [2]:
inertia_mat = uv_body.body_inertia_matrix()
M_func = Function('M_b', [m, I_o, z_g, decoupled_added_m, coupled_added_m], [inertia_mat]) # for numerical & symbolic use

In [3]:
# example usage of inertia mat
M_mat = np.array(M_func(ps.m, ps.Io, ps.rg[2], ps.added_m, ps.coupl_added_m))
M_mat

array([[17.  ,  0.  ,  0.  ,  0.  ,  0.23,  0.  ],
       [ 0.  , 24.2 ,  0.  , -0.23,  0.  ,  0.  ],
       [ 0.  ,  0.  , 26.07,  0.  ,  0.  ,  0.  ],
       [ 0.  , -0.23,  0.  ,  0.28,  0.  ,  0.  ],
       [ 0.23,  0.  ,  0.  ,  0.  ,  0.28,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.28]])

In [4]:
M_mat.T == M_mat

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [5]:
inertia_ned_mat = uv_ned.ned_euler_inertia_matrix()
Onb = vertcat(thet, phi, psi)
M_ned_func = Function('M_ned', [m, I_o, z_g, Onb, decoupled_added_m, coupled_added_m], [inertia_ned_mat]) # for numerical & symbolic use

In [6]:
# example usage of inertia mat in ned
Onb_v = np.array([0.13,0.17,0.1])
np.array(M_ned_func(ps.m, ps.Io, ps.rg[2], Onb_v,  ps.added_m, ps.coupl_added_m))

array([[ 1.72303360e+01, -7.45090577e-01,  1.18405662e+00,
         1.76115723e-02,  2.23648786e-01,  3.57838329e-02],
       [-7.45090577e-01,  2.41747103e+01, -1.91929773e-01,
        -2.26055609e-01,  2.24397276e-02,  3.31239544e-02],
       [ 1.18405662e+00, -1.91929773e-01,  2.58649536e+01,
        -3.85835972e-02, -2.93860503e-02,  0.00000000e+00],
       [ 1.76115723e-02, -2.26055609e-01, -3.85835972e-02,
         2.80000000e-01,  0.00000000e+00, -3.62975599e-02],
       [ 2.23648786e-01,  2.24397276e-02, -2.93860503e-02,
         0.00000000e+00,  2.80000000e-01,  0.00000000e+00],
       [ 3.57838329e-02,  3.31239544e-02,  0.00000000e+00,
        -3.62975599e-02,  0.00000000e+00,  2.80000000e-01]])

<h1>Coriolis Matrix example</h1>

In [7]:
coriolis_mat = uv_body.body_coriolis_centripetal_matrix()
C_func = Function('C_b', [m, I_o, z_g, decoupled_added_m, coupled_added_m, x_nb, v_c], [coriolis_mat]) # for numerical & symbolic use

In [8]:
C = np.array(C_func(ps.m, ps.Io, ps.rg[2], ps.added_m, ps.coupl_added_m, np.array([0.1 ,0.2,0.1,0.1,0.1,0.5]), 
                    np.array([0.0 ,0.0,0.0,0.0,0.0,0.0])))

In [9]:
-C.T == C

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])